create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null,
  role text not null default 'learner',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_records (
  user_id uuid not null references auth.users(id) on delete cascade,
  knowledge_point_id bigint not null,
  topic_id bigint not null,
  grade_id bigint null,
  grade_name text null,
  module_name text null,
  topic_name text null,
  knowledge_point_name text null,
  state text not null default 'not_started',
  started_at timestamptz null,
  completed_at timestamptz null,
  attempts_count integer not null default 0,
  latest_score integer null,
  last_submitted_at timestamptz null,
  last_active_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, knowledge_point_id)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  knowledge_point_id bigint not null,
  topic_id bigint not null,
  grade_id bigint null,
  grade_name text null,
  module_name text null,
  topic_name text null,
  knowledge_point_name text null,
  score integer not null,
  total_questions integer not null,
  correct_count integer not null,
  submitted_at timestamptz not null default now(),
  results jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists learning_records_user_last_active_idx
  on public.learning_records (user_id, last_active_at desc);

create index if not exists learning_records_topic_idx
  on public.learning_records (user_id, topic_id);

create index if not exists quiz_attempts_user_submitted_idx
  on public.quiz_attempts (user_id, submitted_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.email, '用户'),
    coalesce(new.raw_user_meta_data ->> 'role', 'learner')
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = excluded.display_name,
        role = excluded.role,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.learning_records enable row level security;
alter table public.quiz_attempts enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "learning_records_select_own" on public.learning_records;
create policy "learning_records_select_own"
  on public.learning_records for select
  using (auth.uid() = user_id);

drop policy if exists "learning_records_insert_own" on public.learning_records;
create policy "learning_records_insert_own"
  on public.learning_records for insert
  with check (auth.uid() = user_id);

drop policy if exists "learning_records_update_own" on public.learning_records;
create policy "learning_records_update_own"
  on public.learning_records for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "learning_records_delete_own" on public.learning_records;
create policy "learning_records_delete_own"
  on public.learning_records for delete
  using (auth.uid() = user_id);

drop policy if exists "quiz_attempts_select_own" on public.quiz_attempts;
create policy "quiz_attempts_select_own"
  on public.quiz_attempts for select
  using (auth.uid() = user_id);

drop policy if exists "quiz_attempts_insert_own" on public.quiz_attempts;
create policy "quiz_attempts_insert_own"
  on public.quiz_attempts for insert
  with check (auth.uid() = user_id);

drop policy if exists "quiz_attempts_update_own" on public.quiz_attempts;
create policy "quiz_attempts_update_own"
  on public.quiz_attempts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
